-- server/startline.lua
-- Per-track MANUAL START SPAWNS: the two points the split race start puts the
-- field on, placed by hand in game with /setstart (client/startline.lua).
--
-- WHY
--
-- The race start is split mode: half the field on one point, half on another.
-- Normally those points are COMPUTED from start_coords ± SplitPointGap along the
-- right-hand axis of start_heading. Both inputs come from the converted track
-- files, and when either is off for a track, both packs land wrong. A surveyed
-- point — somebody parked there, facing down the track — cannot be off.
--
-- Each stored point has its own heading. server/world.lua builds the race-start
-- grid from them directly; start_coords/start_heading are moved to the midpoint
-- and mean heading so the warmup grid, flag girl and start camera follow.
--
-- WHERE IT IS STORED
--
-- data/start_lines.json (the name predates the switch from a start LINE to two
-- spawn POINTS; older line entries are still read — see pointsOf). NOT
-- data/tracks.lua: that file is generated by tools/convert_tracks.js and every
-- hand edit in it is lost the next time the converter runs.

local FILE = "data/start_lines.json"

local Lines = {}    -- trackId -> { left = {x,y,z}, right = {x,y,z}, heading, by, at }

-- ── Access ───────────────────────────────────────────────────────────────────
--
-- OPEN by default — see Config.StartLineTool in config.lua for the why and for
-- how to lock it back down.
--
-- The short version: the ACE gate this used to have was a wall, not a gate.
-- `spz.dev` is granted to group.admin in spz-txrecipe/server.cfg but nothing is
-- ever put IN group.admin (the add_principal beside it is commented out), and
-- the obvious runtime fix, `set spz_dev true`, is refused by FXServer's
-- production console lockdown. The tool shipped unusable.
local function CanEdit(src)
    if src == 0 then return true end                      -- server console
    local cfg = (Config and Config.StartLineTool) or {}
    if cfg.RequireAce ~= true then return true end        -- open (default)
    if GetConvar("spz_dev", "false") == "true" then return true end
    return IsPlayerAceAllowed(src, "spz.dev")
end

--- Said once at startup, not on every use: an open write-to-disk tool is worth
--- knowing about in the log of a server you thought was locked down, and worth
--- nothing as a line that scrolls past on every command.
CreateThread(function()
    local cfg = (Config and Config.StartLineTool) or {}
    if cfg.RequireAce ~= true then
        print("^3[spz-races] /setstart is OPEN — any player can move a track's start line, "
            .. "and it is written to disk. Set Config.StartLineTool.RequireAce = true to lock it.^7")
    end
end)

local function notify(src, msg, kind)
    TriggerClientEvent("ox_lib:notify", src, {
        description = msg, type = kind or "inform", position = "center-left",
    })
end

--- Refuse, and make sure the player HEARS it.
---
--- Every reason this tool can decline lives on the server, and the client has
--- no way to tell "refused" apart from "never arrived" — so a refusal that only
--- logged here read, from the driving seat, as a command that does not exist.
--- This answers on a dedicated event (which also cancels the client's
--- no-reply timeout) and prints server-side, so there is a trace on both ends.
local function refuse(src, msg)
    print(("^3[spz-races] /setstart refused for %s (%s): %s^7")
        :format(GetPlayerName(src) or "?", tostring(src), msg))
    TriggerClientEvent("spz-startline:refused", src, msg)
    notify(src, msg, "error")
end

--- Print the exact server.cfg lines that would grant this player access.
---
--- Being told "you need ACE spz.dev" is not the same as being able to act on
--- it: the grant needs an identifier this player actually owns, and the obvious
--- next move — typing `set spz_dev true` into the live console — is refused
--- outright on any server running FXServer's production console lockdown, which
--- blocks `set`, `add_ace` and `add_principal` at runtime. They are only
--- honoured when parsed from server.cfg at startup.
---
--- So the lock prints copy-paste-ready config instead of a rule to go and look
--- up. Console only: identifiers are not something to broadcast to a client.
local function printGrantHelp(src)
    print("^3[spz-races] ── how to grant access ─────────────────────────────^7")
    print("^3  These go in server.cfg and take effect on restart. They are")
    print("  REFUSED from the live console if this server runs in production")
    print("  mode (https://aka.cfx.re/prod-console).^7")
    print("")
    print("^2  Per-person, recommended — pick ONE identifier below:^7")

    local ids = GetPlayerIdentifiers(src) or {}
    local shown = 0
    for _, id in ipairs(ids) do
        -- license is the stable one; steam/fivem are fine too. ip is not an
        -- identity and is never worth suggesting.
        if not id:match("^ip:") then
            shown = shown + 1
            print(("^2    add_ace identifier.%s spz.dev allow^7"):format(id))
        end
    end
    if shown == 0 then
        print("^1    (no usable identifiers — is the player fully connected?)^7")
    end

    print("")
    print("^3  Or, if you are already in an admin group:^7")
    print("^3    add_principal identifier.<yours> group.admin^7")
    print("^3    ...group.admin already has spz.dev in spz-txrecipe/server.cfg.^7")
    print("")
    print("^1  LOCAL DEV BOXES ONLY — opens the tool to every player on the^7")
    print("^1  server, so never on anything public:^7")
    print("^1    set spz_dev true^7")   -- plain `set`: only the server reads it
    print("^3[spz-races] ────────────────────────────────────────────────────^7")
end

-- ── Geometry ─────────────────────────────────────────────────────────────────

local function dist2(a, b)
    local dx, dy = a.x - b.x, a.y - b.y
    return math.sqrt(dx * dx + dy * dy)
end

-- ── Persistence ──────────────────────────────────────────────────────────────

local function Load()
    local raw = LoadResourceFile(GetCurrentResourceName(), FILE)
    if not raw then return end
    local ok, parsed = pcall(json.decode, raw)
    if ok and type(parsed) == "table" then Lines = parsed end
end

local function Save()
    SaveResourceFile(GetCurrentResourceName(), FILE, json.encode(Lines, { indent = true }), -1)
end

--- Write one stored line onto the live track. Returns false when the track is
--- not loaded — which happens legitimately: a line can outlive the track it was
--- set on if that track is later renamed or dropped from the converter output.
--- Circular mean of two headings, so 350° and 10° average to 0°, not 180°.
local function meanHeading(h1, h2)
    local r1, r2 = math.rad(h1), math.rad(h2)
    return math.deg(math.atan(math.sin(r1) + math.sin(r2), math.cos(r1) + math.cos(r2))) % 360.0
end

--- Stored entry -> the two spawn points, in { x, y, z, h } form.
---
--- Entries saved by the earlier start-LINE version of this tool have `left`,
--- `right` and one `heading` instead of `points`; they are read as two points
--- sharing that heading, so nothing already saved is lost.
local function pointsOf(e)
    if e.points and e.points[1] and e.points[2] then return e.points end
    if e.left and e.right then
        local h = e.heading or 0.0
        return {
            { x = e.left.x,  y = e.left.y,  z = e.left.z,  h = h },
            { x = e.right.x, y = e.right.y, z = e.right.z, h = h },
        }
    end
    return nil
end

--- Put a track's two manual spawn points onto the live track.
---
--- `start_points` is what server/world.lua builds the race-start grid from:
--- one pack on each point, facing that point's own heading, instead of two
--- packs computed from start_coords ± SplitPointGap. start_coords and
--- start_heading are ALSO moved — to the midpoint and the mean heading — so
--- everything else that reads them (the warmup grid, the flag girl's mark, the
--- start camera) stays centred on the same place the racers now start from.
local function Apply(trackId)
    local e     = Lines[trackId]
    local track = SPZ.Tracks and SPZ.Tracks[trackId]
    if not e or not track then return false end

    local pts = pointsOf(e)
    if not pts then return false end

    local p1 = vector3(pts[1].x, pts[1].y, pts[1].z)
    local p2 = vector3(pts[2].x, pts[2].y, pts[2].z)

    track.start_points = {
        { coords = p1, heading = (pts[1].h or 0.0) % 360.0 },
        { coords = p2, heading = (pts[2].h or 0.0) % 360.0 },
    }
    track.start_coords  = (p1 + p2) * 0.5
    track.start_heading = meanHeading(pts[1].h or 0.0, pts[2].h or 0.0)

    return true, dist2(pts[1], pts[2])
end

local function ApplyAll()
    local n = 0
    for id in pairs(Lines) do
        if Apply(id) then n = n + 1 end
    end
    return n
end

-- Load order matters and is not obvious.
--
-- SPZ.Tracks comes from data/tracks.lua, which is loaded as a server script, so
-- it exists by the time any thread runs. Custom tracks are added by
-- server/creator.lua from its own CreateThread — and threads run in creation
-- order, so this file MUST stay listed after creator.lua in fxmanifest.lua or a
-- line set on a custom track would be applied before that track exists and
-- silently do nothing.
CreateThread(function()
    Load()
    local n, total = ApplyAll(), 0
    for _ in pairs(Lines) do total = total + 1 end
    if total > 0 then
        print(("^2[spz-races] start lines: applied %d of %d from %s^7"):format(n, total, FILE))
        if n < total then
            print("^3[spz-races] ...the rest name tracks that are not loaded (renamed or dropped?)^7")
        end
    end
end)

-- ── Net events ───────────────────────────────────────────────────────────────

--- The WHOLE track list, the way /fixheadings works (server/dev_heading.lua):
--- the client walks it with the arrow keys and teleports to each start, so one
--- session covers every track. Each entry carries its saved points (if any), the
--- next gate (so "down the track" is visible) and gate 1's posts as a reference
--- for where the road edges are.
RegisterNetEvent("spz-startline:reqList", function()
    local src = source
    print(("^5[spz-races] /setstart list requested by %s (%s)^7")
        :format(GetPlayerName(src) or "?", tostring(src)))

    if not CanEdit(src) then
        refuse(src, "Start-line tool is locked on this server — see the console for the grant line.")
        printGrantHelp(src)
        return
    end

    local ped = GetPlayerPed(src)
    local pos = (ped ~= 0) and GetEntityCoords(ped) or nil

    local list = {}
    for id, t in pairs(SPZ.Tracks or {}) do
        if t.start_coords then
            local nextCp, gate1
            for i, cp in ipairs(t.checkpoints or {}) do
                if i == 1 and cp.left and cp.right then
                    gate1 = {
                        left  = { x = cp.left.x,  y = cp.left.y,  z = cp.left.z },
                        right = { x = cp.right.x, y = cp.right.y, z = cp.right.z },
                    }
                end
                if not nextCp and cp.coords and dist2(cp.coords, t.start_coords) > 5.0 then
                    nextCp = { x = cp.coords.x, y = cp.coords.y, z = cp.coords.z }
                end
            end

            local l = Lines[id] and pointsOf(Lines[id])
            list[#list + 1] = {
                id      = id,
                name    = t.name or id,
                type    = t.type or "circuit",
                start   = { x = t.start_coords.x, y = t.start_coords.y, z = t.start_coords.z },
                heading = t.start_heading or 0.0,
                nextCp  = nextCp,
                gate1   = gate1,
                points  = l,
                dist    = pos and dist2(t.start_coords, pos) or nil,
            }
        end
    end

    if #list == 0 then
        return refuse(src, "No tracks loaded — is data/tracks.lua present?")
    end

    table.sort(list, function(a, b) return a.name:lower() < b.name:lower() end)

    -- Open on the track you are standing at, if any is close, rather than on
    -- whatever sorts first alphabetically.
    local startIdx, best = 1, nil
    for i, e in ipairs(list) do
        if e.dist and (not best or e.dist < best) then startIdx, best = i, e.dist end
    end
    if best and best > 300.0 then startIdx = 1 end

    print(("^5[spz-races] /setstart -> sent %d tracks to %s^7"):format(#list, GetPlayerName(src) or "?"))
    TriggerClientEvent("spz-startline:list", src, list, startIdx)
end)

RegisterNetEvent("spz-startline:save", function(trackId, p1, p2)
    local src = source
    if not CanEdit(src) then return refuse(src, "Start-point tool is locked on this server.") end
    if type(trackId) ~= "string" or trackId == "" then return refuse(src, "No track id.") end
    if type(p1) ~= "table" or type(p2) ~= "table" then return refuse(src, "Bad points.") end

    -- Rewriting a track's start while a race runs on it would move the grid,
    -- the flag girl and the start camera out from under people already on it.
    local st = GlobalState.raceState
    if st and st ~= "IDLE" and st ~= "POLLING" then
        return refuse(src, ("Race is %s — set spawn points between races."):format(tostring(st)))
    end

    local track = SPZ.Tracks and SPZ.Tracks[trackId]
    if not track then return refuse(src, ("No track '%s'."):format(trackId)) end

    local function clean(p)
        local q = { x = tonumber(p.x), y = tonumber(p.y), z = tonumber(p.z), h = tonumber(p.h) }
        if not (q.x and q.y and q.z and q.h) then return nil end
        q.h = q.h % 360.0
        return q
    end
    local a, b = clean(p1), clean(p2)
    if not (a and b) then
        return refuse(src, "Captured points were malformed — re-take them with [R] then [E].")
    end

    -- Two packs on the same spot is the stacked start split mode exists to
    -- avoid; two packs a street apart is not one grid.
    local gap = dist2(a, b)
    if gap < 2.0 then
        return refuse(src, ("Points are only %.1f m apart — the two packs would overlap."):format(gap))
    end
    if gap > 60.0 then
        return refuse(src, ("Points are %.0f m apart — that is not one start."):format(gap))
    end

    Lines[trackId] = {
        points = { a, b },
        by     = GetPlayerName(src),
        at     = os.date("%Y-%m-%d %H:%M:%S"),
    }
    Save()
    Apply(trackId)

    print(("[spz-races] spawn points saved for '%s': %.1f m apart, headings %.1f° / %.1f°")
        :format(trackId, gap, a.h, b.h))
    notify(src, ("Saved %s — %.1f m apart"):format(trackId, gap), "success")
    TriggerClientEvent("spz-startline:saved", src, trackId, gap, { a, b })
end)

RegisterNetEvent("spz-startline:clear", function(trackId)
    local src = source
    if not CanEdit(src) then return refuse(src, "Start-line tool is locked on this server.") end
    if type(trackId) ~= "string" or not Lines[trackId] then
        return refuse(src, ("No stored line for '%s'."):format(tostring(trackId)))
    end

    Lines[trackId] = nil
    Save()
    -- The live track keeps the applied values until the next restart. Saying so
    -- is better than pretending the revert already happened: the original
    -- coords live in data/tracks.lua and are only re-read when it is loaded.
    if SPZ.Tracks and SPZ.Tracks[trackId] then SPZ.Tracks[trackId].start_points = nil end
    notify(src, ("Cleared %s — the original start returns on restart."):format(trackId), "success")
end)

-- ── Console ──────────────────────────────────────────────────────────────────

RegisterCommand("startlines", function(src)
    if src ~= 0 and not CanEdit(src) then return end
    local n = 0
    print("^5── manual spawn points ─────────────────────────────^7")
    for id, e in pairs(Lines) do
        local pts = pointsOf(e)
        if pts then
            n = n + 1
            print(("  %-24s %6.1f m apart  %6.1f° / %6.1f°  %s  %s")
                :format(id, dist2(pts[1], pts[2]), pts[1].h or 0, pts[2].h or 0, e.at or "?", e.by or "?"))
        end
    end
    if n == 0 then print("  none — set one in game with /setstart") end
    print(("^5── %d override(s) · %s ─────────────^7"):format(n, FILE))
end, true)
