-- server/startline.lua
-- Per-track START LINE: two points on the road instead of one point and a
-- guessed heading.  Set in game with /setstart (client/startline.lua).
--
-- WHY TWO POINTS
--
-- A track's start is `start_coords` plus `start_heading` — a single coordinate
-- and an angle, and the angle is the problem. It is whatever the converter
-- pulled out of the source track file, and when it is wrong the whole grid
-- faces the wrong way. There is already a dev tool whose entire purpose is
-- walking every track fixing them by hand (client/dev_heading.lua).
--
-- Two points do not need an angle. Stand at one edge of the road, stand at the
-- other, and the line between them IS the start line: the midpoint is where the
-- grid goes and the perpendicular is which way it faces. That is the same shape
-- a checkpoint already has — `left` and `right` posts with the plane derived
-- from them — so the start line stops being the one piece of track geometry
-- described differently from every other piece.
--
-- WHERE IT IS STORED, AND WHY NOT IN THE OBVIOUS PLACE
--
-- NOT in data/tracks.lua. That file says "Auto-generated by
-- tools/convert_tracks.js — do NOT edit coords manually" at the top and means
-- it: re-running the converter rewrites the file and every hand-edit in it is
-- gone. server/dev_heading.lua does write back into it, by regex, and every
-- heading it has ever fixed is one converter run away from being lost.
--
-- So this writes a SEPARATE file, data/start_lines.json, and applies it OVER
-- SPZ.Tracks at load. Regenerating tracks.lua cannot touch it, and a track
-- whose line has not been set is left exactly as the converter produced it.

local FILE = "data/start_lines.json"

local Lines = {}    -- trackId -> { left = {x,y,z}, right = {x,y,z}, heading, by, at }

-- ── Access ───────────────────────────────────────────────────────────────────
--
-- OPEN by default — see Config.StartLineTool in config.lua for the why and for
-- how to lock it back down.
--
-- The short version: the ACE gate this used to have was a wall, not a gate.
-- `spz.dev` is granted to group.admin in spz-txrecipe/server.cfg but nothing is
-- ever put IN group.admin (the add_principal beside it is commented out), and
-- the obvious runtime fix, `set spz_dev true`, is refused by FXServer's
-- production console lockdown. The tool shipped unusable.
local function CanEdit(src)
    if src == 0 then return true end                      -- server console
    local cfg = (Config and Config.StartLineTool) or {}
    if cfg.RequireAce ~= true then return true end        -- open (default)
    if GetConvar("spz_dev", "false") == "true" then return true end
    return IsPlayerAceAllowed(src, "spz.dev")
end

--- Said once at startup, not on every use: an open write-to-disk tool is worth
--- knowing about in the log of a server you thought was locked down, and worth
--- nothing as a line that scrolls past on every command.
CreateThread(function()
    local cfg = (Config and Config.StartLineTool) or {}
    if cfg.RequireAce ~= true then
        print("^3[spz-races] /setstart is OPEN — any player can move a track's start line, "
            .. "and it is written to disk. Set Config.StartLineTool.RequireAce = true to lock it.^7")
    end
end)

local function notify(src, msg, kind)
    TriggerClientEvent("ox_lib:notify", src, {
        description = msg, type = kind or "inform", position = "center-left",
    })
end

--- Refuse, and make sure the player HEARS it.
---
--- Every reason this tool can decline lives on the server, and the client has
--- no way to tell "refused" apart from "never arrived" — so a refusal that only
--- logged here read, from the driving seat, as a command that does not exist.
--- This answers on a dedicated event (which also cancels the client's
--- no-reply timeout) and prints server-side, so there is a trace on both ends.
local function refuse(src, msg)
    print(("^3[spz-races] /setstart refused for %s (%s): %s^7")
        :format(GetPlayerName(src) or "?", tostring(src), msg))
    TriggerClientEvent("spz-startline:refused", src, msg)
    notify(src, msg, "error")
end

--- Print the exact server.cfg lines that would grant this player access.
---
--- Being told "you need ACE spz.dev" is not the same as being able to act on
--- it: the grant needs an identifier this player actually owns, and the obvious
--- next move — typing `set spz_dev true` into the live console — is refused
--- outright on any server running FXServer's production console lockdown, which
--- blocks `set`, `add_ace` and `add_principal` at runtime. They are only
--- honoured when parsed from server.cfg at startup.
---
--- So the lock prints copy-paste-ready config instead of a rule to go and look
--- up. Console only: identifiers are not something to broadcast to a client.
local function printGrantHelp(src)
    print("^3[spz-races] ── how to grant access ─────────────────────────────^7")
    print("^3  These go in server.cfg and take effect on restart. They are")
    print("  REFUSED from the live console if this server runs in production")
    print("  mode (https://aka.cfx.re/prod-console).^7")
    print("")
    print("^2  Per-person, recommended — pick ONE identifier below:^7")

    local ids = GetPlayerIdentifiers(src) or {}
    local shown = 0
    for _, id in ipairs(ids) do
        -- license is the stable one; steam/fivem are fine too. ip is not an
        -- identity and is never worth suggesting.
        if not id:match("^ip:") then
            shown = shown + 1
            print(("^2    add_ace identifier.%s spz.dev allow^7"):format(id))
        end
    end
    if shown == 0 then
        print("^1    (no usable identifiers — is the player fully connected?)^7")
    end

    print("")
    print("^3  Or, if you are already in an admin group:^7")
    print("^3    add_principal identifier.<yours> group.admin^7")
    print("^3    ...group.admin already has spz.dev in spz-txrecipe/server.cfg.^7")
    print("")
    print("^1  LOCAL DEV BOXES ONLY — opens the tool to every player on the^7")
    print("^1  server, so never on anything public:^7")
    print("^1    set spz_dev true^7")   -- plain `set`: only the server reads it
    print("^3[spz-races] ────────────────────────────────────────────────────^7")
end

-- ── Geometry ─────────────────────────────────────────────────────────────────

local function dist2(a, b)
    local dx, dy = a.x - b.x, a.y - b.y
    return math.sqrt(dx * dx + dy * dy)
end

--- Which way the grid faces, from the line and the track that owns it.
---
--- The perpendicular to a line has TWO directions and the line itself cannot
--- say which is forward — so it is resolved the way the rest of this codebase
--- resolves it: point at the next checkpoint. That also means the order the two
--- points were captured in does not matter, which is the whole reason the
--- command does not ask for "left" and "right".
---
--- Falls back to the track's existing heading when there is no checkpoint far
--- enough away to aim at (a one-gate track, or a first gate sitting on the
--- start line itself).
local function HeadingFor(track, left, right)
    local gx, gy = right.x - left.x, right.y - left.y
    local glen = math.sqrt(gx * gx + gy * gy)
    if glen < 0.01 then return track and track.start_heading or 0.0, false end

    -- Both perpendiculars, as unit vectors.
    local nx, ny = -gy / glen, gx / glen

    local mid = { x = (left.x + right.x) * 0.5, y = (left.y + right.y) * 0.5 }

    local aim
    for _, cp in ipairs((track and track.checkpoints) or {}) do
        if cp.coords and dist2(cp.coords, mid) > 5.0 then aim = cp.coords break end
    end

    if aim then
        -- Flip the normal to the side the next gate is on.
        if ((aim.x - mid.x) * nx + (aim.y - mid.y) * ny) < 0 then
            nx, ny = -nx, -ny
        end
        return math.deg(math.atan(-nx, ny)) % 360.0, true
    end

    return (track and track.start_heading) or (math.deg(math.atan(-nx, ny)) % 360.0), false
end

-- ── Persistence ──────────────────────────────────────────────────────────────

local function Load()
    local raw = LoadResourceFile(GetCurrentResourceName(), FILE)
    if not raw then return end
    local ok, parsed = pcall(json.decode, raw)
    if ok and type(parsed) == "table" then Lines = parsed end
end

local function Save()
    SaveResourceFile(GetCurrentResourceName(), FILE, json.encode(Lines, { indent = true }), -1)
end

--- Write one stored line onto the live track. Returns false when the track is
--- not loaded — which happens legitimately: a line can outlive the track it was
--- set on if that track is later renamed or dropped from the converter output.
local function Apply(trackId)
    local line  = Lines[trackId]
    local track = SPZ.Tracks and SPZ.Tracks[trackId]
    if not line or not track then return false end

    local left  = vector3(line.left.x,  line.left.y,  line.left.z)
    local right = vector3(line.right.x, line.right.y, line.right.z)
    -- dist2, not #(right - left): the save gate below validates the width in
    -- 2D and this is the same quantity. Measuring it two ways is how the
    -- number that was accepted and the number that gets stored drift apart.
    local width = dist2(line.left, line.right)

    track.start_coords  = (left + right) * 0.5
    track.start_heading = line.heading

    -- Kept beside the overridden values rather than folded into them: the pair
    -- is what was actually measured, and the width is the road. Nothing reads
    -- it yet — the grid maths is deliberately untouched (see the note in
    -- Config.WarmupSpawnMode about why the race start is one point) — but a
    -- start line that threw away its own width would have to be re-surveyed the
    -- first time anything wanted it.
    track.start_line = { left = left, right = right, width = width }

    return true, width
end

local function ApplyAll()
    local n = 0
    for id in pairs(Lines) do
        if Apply(id) then n = n + 1 end
    end
    return n
end

-- Load order matters and is not obvious.
--
-- SPZ.Tracks comes from data/tracks.lua, which is loaded as a server script, so
-- it exists by the time any thread runs. Custom tracks are added by
-- server/creator.lua from its own CreateThread — and threads run in creation
-- order, so this file MUST stay listed after creator.lua in fxmanifest.lua or a
-- line set on a custom track would be applied before that track exists and
-- silently do nothing.
CreateThread(function()
    Load()
    local n, total = ApplyAll(), 0
    for _ in pairs(Lines) do total = total + 1 end
    if total > 0 then
        print(("^2[spz-races] start lines: applied %d of %d from %s^7"):format(n, total, FILE))
        if n < total then
            print("^3[spz-races] ...the rest name tracks that are not loaded (renamed or dropped?)^7")
        end
    end
end)

-- ── Net events ───────────────────────────────────────────────────────────────

--- The track the player is standing on, plus whatever line it already has.
--- Nearest by existing start point, because that is the thing being replaced.
RegisterNetEvent("spz-startline:request", function(wantedId)
    local src = source
    print(("^5[spz-races] /setstart request from %s (%s), track=%s^7")
        :format(GetPlayerName(src) or "?", tostring(src), tostring(wantedId or "nearest")))

    if not CanEdit(src) then
        refuse(src, "Start-line tool is locked on this server — see the console for the grant line.")
        printGrantHelp(src)
        return
    end

    local ped = GetPlayerPed(src)
    -- Was a bare `return`. A player whose ped has not finished spawning got
    -- absolute silence, which is the single worst thing this tool can do.
    if ped == 0 then
        return refuse(src, "Your ped is not spawned yet — try again in a moment.")
    end
    local pos = GetEntityCoords(ped)

    local id, track, best
    if wantedId and wantedId ~= "" then
        id, track = wantedId, SPZ.Tracks and SPZ.Tracks[wantedId]
        if not track then return refuse(src, ("No track '%s'. See /startlines on the server console."):format(wantedId)) end
    else
        local scanned = 0
        for tid, t in pairs(SPZ.Tracks or {}) do
            if t.start_coords then
                scanned = scanned + 1
                local d = dist2(t.start_coords, pos)
                if not best or d < best then id, track, best = tid, t, d end
            end
        end
        if not track then
            return refuse(src, ("No usable tracks loaded (%d scanned). Is data/tracks.lua present?"):format(scanned))
        end
    end

    local existing = Lines[id]
    local nextCp
    for _, cp in ipairs(track.checkpoints or {}) do
        if cp.coords and dist2(cp.coords, track.start_coords) > 5.0 then
            nextCp = { x = cp.coords.x, y = cp.coords.y, z = cp.coords.z }
            break
        end
    end

    TriggerClientEvent("spz-startline:open", src, {
        id      = id,
        name    = track.name or id,
        type    = track.type or "circuit",
        start   = { x = track.start_coords.x, y = track.start_coords.y, z = track.start_coords.z },
        heading = track.start_heading or 0.0,
        nextCp  = nextCp,
        line    = existing and { left = existing.left, right = existing.right, heading = existing.heading } or nil,
        distance = best,
    })
end)

RegisterNetEvent("spz-startline:save", function(trackId, left, right)
    local src = source
    if not CanEdit(src) then return refuse(src, "Start-line tool is locked on this server.") end
    if type(trackId) ~= "string" or trackId == "" then return refuse(src, "No track id.") end
    if type(left) ~= "table" or type(right) ~= "table" then return refuse(src, "Bad points.") end

    -- Not a permissions question, and it stays whatever Config.StartLineTool
    -- says: rewriting a track's start point while a race is running on it moves
    -- the grid, the flag girl's mark and the start camera out from under people
    -- who are already on it. server/world.lua reads start_coords at setup and
    -- server/countdown.lua reads the heading again after that, so a save landing
    -- between them splits the two. Survey between races.
    local st = GlobalState.raceState
    if st and st ~= "IDLE" and st ~= "POLLING" then
        return refuse(src, ("Race is %s — set the start line between races."):format(tostring(st)))
    end

    local track = SPZ.Tracks and SPZ.Tracks[trackId]
    if not track then return notify(src, ("No track '%s'."):format(trackId), "error") end

    local l = { x = tonumber(left.x),  y = tonumber(left.y),  z = tonumber(left.z) }
    local r = { x = tonumber(right.x), y = tonumber(right.y), z = tonumber(right.z) }
    if not (l.x and l.y and l.z and r.x and r.y and r.z) then
        return refuse(src, "Captured points were malformed — re-take them with [R] then [E].")
    end

    local width = dist2(l, r)
    -- Two points in the same place is not a line, and the failure it causes is
    -- silent: the perpendicular is undefined, so the heading falls back and the
    -- grid faces wherever it did before. Better to refuse it.
    if width < 2.0 then
        return notify(src, ("Points are %.1f m apart — stand at both edges of the road."):format(width), "error")
    end
    if width > 60.0 then
        return notify(src, ("%.0f m apart — that is not one start line."):format(width), "error")
    end

    local heading, aimed = HeadingFor(track, l, r)

    Lines[trackId] = {
        left    = l,
        right   = r,
        heading = heading,
        by      = GetPlayerName(src),
        at      = os.date("%Y-%m-%d %H:%M:%S"),
    }
    Save()
    Apply(trackId)

    print(("[spz-races] start line saved for '%s': %.1f m wide, heading %.2f (%s)")
        :format(trackId, width, heading, aimed and "aimed at next gate" or "no gate to aim at"))
    notify(src, ("Saved %s — %.1f m wide, facing %.1f°%s")
        :format(trackId, width, heading, aimed and "" or " (no next gate — kept old heading)"), "success")

    TriggerClientEvent("spz-startline:saved", src, trackId, heading, width)
end)

RegisterNetEvent("spz-startline:clear", function(trackId)
    local src = source
    if not CanEdit(src) then return refuse(src, "Start-line tool is locked on this server.") end
    if type(trackId) ~= "string" or not Lines[trackId] then
        return refuse(src, ("No stored line for '%s'."):format(tostring(trackId)))
    end

    Lines[trackId] = nil
    Save()
    -- The live track keeps the applied values until the next restart. Saying so
    -- is better than pretending the revert already happened: the original
    -- coords live in data/tracks.lua and are only re-read when it is loaded.
    if SPZ.Tracks and SPZ.Tracks[trackId] then SPZ.Tracks[trackId].start_line = nil end
    notify(src, ("Cleared %s — the original start returns on restart."):format(trackId), "success")
end)

-- ── Console ──────────────────────────────────────────────────────────────────

RegisterCommand("startlines", function(src)
    if src ~= 0 and not CanEdit(src) then return end
    local n = 0
    print("^5── start line overrides ────────────────────────────^7")
    for id, l in pairs(Lines) do
        n = n + 1
        local width = dist2(l.left, l.right)
        print(("  %-24s %6.1f m  %7.2f°  %s  %s")
            :format(id, width, l.heading or 0.0, l.at or "?", l.by or "?"))
    end
    if n == 0 then print("  none — set one in game with /setstart") end
    print(("^5── %d override(s) · %s ─────────────^7"):format(n, FILE))
end, true)
