-- shared/sectors.lua
-- Every track is split into 3 sectors by checkpoint count.
--
-- Sectors are derived here rather than stored in data/tracks.lua: that file is
-- generated by convert_tracks.py and carries a "do NOT edit" banner, so any
-- hand-added sector data there is destroyed on the next regeneration. Deriving
-- also means new tracks get sectors for free.

if not SPZ then SPZ = {} end

local cache = {}

-- Boundaries for a track: 3 entries of { first = cpIndex, last = cpIndex }.
-- The remainder of an uneven split goes to the earlier sectors, so 25 CPs
-- becomes 9/8/8. Tracks with fewer than 3 checkpoints get one sector per CP and
-- empty sectors are dropped by the callers via `last >= first`.
function SPZ.GetTrackSectors(track)
    if not track or not track.checkpoints then return nil end

    local key = track.name or tostring(track)
    if cache[key] then return cache[key] end

    local total = #track.checkpoints
    local base  = math.floor(total / 3)
    local extra = total % 3

    local bounds, cursor = {}, 1
    for i = 1, 3 do
        local size = base + (i <= extra and 1 or 0)
        bounds[i] = { first = cursor, last = cursor + size - 1 }
        cursor = cursor + size
    end

    cache[key] = bounds
    return bounds
end

-- Which sector (1..3) a checkpoint index belongs to, or nil if out of range.
function SPZ.SectorForCP(track, cpIndex)
    local bounds = SPZ.GetTrackSectors(track)
    if not bounds then return nil end

    for i = 1, 3 do
        if cpIndex >= bounds[i].first and cpIndex <= bounds[i].last then
            return i
        end
    end
    return nil
end

-- True when this checkpoint closes a sector (i.e. the sector clock stops here).
function SPZ.IsSectorEnd(track, cpIndex)
    local bounds = SPZ.GetTrackSectors(track)
    if not bounds then return nil end

    for i = 1, 3 do
        if bounds[i].last == cpIndex and bounds[i].last >= bounds[i].first then
            return i
        end
    end
    return nil
end
